### ISSUE TITLE
Generating initial reactive trajectory

### ISSUE THREAD

**Issue by smlee99** [ansingh1214/TPS-U-OpenMM#1]
Hi. I'm trying to compute the rate constant at interfacial system and looks like TPS+U method is a good way to go. Thanks for the distribution of TPS+U open source code! Currently, I'm trying to reproduce the result in [here](https://pubs.acs.org/doi/10.1021/acs.jpclett.1c03837). Can I request for the code or module that you've used to generate the initial reactive trajectory? It would be highly appreciated if you can introduce the code or module that you've used to reweight the TPS simulation result. Thanks in advance!

**Comment by ansingh1214** [comment]
For generating the first reactive trajectory you can do one of the following:

Start in the metastable well A and run the simulation at a high temperature (say 500 K). This would accelerate the A->B transition, and then you can use the same algorithm (remember to account for the change in velocity distribution when you perform TPS at whatever temperature you are interested in by modifying the acceptance criteria). An example is shown [here](http://openpathsampling.org/latest/examples/AD_fixed_len_tps.html).

Alternatively, you can use a harmonic potential to constrain the system at the barrier along the progress coordinate and the specific value of z (distance from the interface) that you are interested.  Then you can chose a configuration from this constrained simulation, and run a forward and 'backward' simulation. You can do this by initializing the configurations with some velocity drawn from a Maxwell Boltzmann Distribution (openmm has a [module](https://simtk.org/api_docs/openmm/api5_0/python/classsimtk_1_1openmm_1_1openmm_1_1Context.html#) for it), say v0. Then you run two simulations with it each for tf/2 seconds (where tf is the length of the TPS trajectory), one where the initial velocity is v0 and another where the initial velocity is -v0. If one of these trajectories ends up in well A and if the other one ends up in well B (or vice versa), then you can invert one of the two and join them together.

For reweighting you can use the [Grossfield Lab implementation of WHAM](http://membrane.urmc.rochester.edu/?page_id=126).

**Comment by smlee99** [comment]
Many thanks to your reply! I have generated the initial reactive trajectory following your second suggestion. Just for a small question. While reading the manual of Grossfield Lab WHAM, I've found that for each window, time series file should be written during the simulation (which will be stitched into a metafile). In such file, the thing that should be written "per every trial" is the reactive probability p (if reactive, p=tps_u_bias*N_prev/N, o.w. p=0), right? I wonder if I understood this correctly or not.

**Comment by smlee99** [comment]
Oh or should I write the z value of initial and final frame configuration in accepted reactive trajectory candidate?

**Comment by ansingh1214** [comment]
It is the z values that you write at each step. If the new trajectory is accepted, you should store the z value of the new trajectory or else you should store the z value of the old trajectory. Ideally the z value at the 'barrier region' of the path should be selected, although it usually doesn't matter in the case that the diffusion along over the path length is minimal. This is also discussed in the original TPS+U [paper](https://aip.scitation.org/doi/pdf/10.1063/1.5092837), right below equation 6.

**Comment by smlee99** [comment]
Sorry for late reply. Thanks for your advice and I guess now I'm on the right track! By the way, I heard your talk at 2023 APS March Meeting in Las Vegas and it was really good :) Let me close this issue.

**Comment by ansingh1214** [comment]
Glad to see the issue resolved, and thanks a lot for stopping by for my talk 😄
